"""Job recommendation schemas."""
from pydantic import BaseModel, Field
from typing import Optional


class JobListing(BaseModel):
    """A single recommended job posting."""
    id: str
    company: str
    title: str
    location: str
    description: str = Field(description="Truncated JD")
    salary_text: Optional[str] = None  # e.g. "₹14-22 LPA" or "$80k-110k"
    url: str
    match_score: int = Field(ge=0, le=100, description="Semantic + role-fit blend")
    why_fits: list[str] = Field(
        default_factory=list,
        description="2-3 reasons this candidate fits, generated by LLM",
    )
    posted_age: Optional[str] = None  # e.g. "2 days ago"


class JobsResponse(BaseModel):
    jobs: list[JobListing]
    total_found: int
    sources: list[str] = Field(description="Where the jobs came from")
